//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS1A
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_master_1A
    {
        public int UserCode { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string application_user { get; set; }
        public string application_user_type { get; set; }
        public string employee_id { get; set; }
        public string user_appl { get; set; }
        public Nullable<int> Commitee { get; set; }
        public string UserDesc { get; set; }
        public Nullable<System.DateTime> Cyear { get; set; }
        public string Dept { get; set; }
        public string TelePhone { get; set; }
    }
}
